In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import hypertools as hyp
import seaborn as sns
%matplotlib notebook

In [2]:
#load in the data

fname = 'At Risk Students For Dartmouth.xlsx'
sheet1 = 'Year 16-17'
sheet2 = 'Year 17-18 9.25.17'
columns = ('id', 'grade', 'age', 'school', 'sex', 'homeless', 'disadvantaged', 'specialneeds',
           'excused1', 'unexcused1', 'tardy1',
           'excused2', 'unexcused2', 'tardy2',
           'excused3', 'unexcused3', 'tardy3',
           'excused4', 'unexcused4', 'tardy4')
y1_data = pd.read_excel(fname, sheetname=sheet1, skiprows=[0], names=columns)
y2_data = pd.read_excel(fname, sheetname=sheet2, skiprows=[0], names=columns)

#use student IDs as the index
y1_data.set_index('id', inplace=True)
y2_data.set_index('id', inplace=True)

In [3]:
#do some data cleaning

#in "disadvantaged" column, replace "YES" with 1 and NaN with 0
y1_data['disadvantaged'] = y1_data['disadvantaged'].map({np.nan: 0, 'YES': 1})
y2_data['disadvantaged'] = y2_data['disadvantaged'].map({np.nan: 0, 'YES': 1})

#in "disadvantaged" column, replace "YES" with 1 and NaN with 0
#y1_data['specialneeds'] = y1_data['specialneeds'].map({np.nan: '', '504': 504, 'IEP': IEP  })
#y1_data['specialneeds'] = y2_data['specialneeds'].map({np.nan: '', '504': 504, 'IEP': IEP  })

#replace '---' with 0 (Fourth marking period columns)
y1_data.replace('---', 0, inplace=True)
y2_data.replace('---', 0, inplace=True)

In [4]:
y1_data.head()

,grade,age,school,sex,homeless,disadvantaged,specialneeds,excused1,unexcused1,tardy1,excused2,unexcused2,tardy2,excused3,unexcused3,tardy3,excused4,unexcused4,tardy4
id,,,,,,,,,,,,,,,,,,,
300053,10,16,Hartford High School/HACTC,F,N,1,NaN,22,0,0,0,0,0,0,0,1,2,2,0
300339,12,18,Hartford High School/HACTC,F,N,0,NaN,4,2,4,13,9,6,27,15,5,36,15,7
300340,11,17,Hartford High School/HACTC,M,N,0,NaN,1,0,0,5,1,1,3,0,5,24,0,1
300344,9,15,Hartford High School/HACTC,M,N,0,NaN,0,0,0,15,0,0,0,1,0,3,0,0
300345,8,15,Hartford Memorial Middle School,M,N,0,504,0,0,0,3,0,1,4,0,1,5,0,3

In [5]:
pd.unique(y1_data['specialneeds'])

array([nan, 504, 'IEP'], dtype=object)

In [6]:
y1_data['total_debauchery'] = y1_data['unexcused2'] + y1_data['unexcused1']+ y1_data['unexcused3']+ y1_data['unexcused4']
y1_data

,grade,age,school,sex,homeless,disadvantaged,specialneeds,excused1,unexcused1,tardy1,excused2,unexcused2,tardy2,excused3,unexcused3,tardy3,excused4,unexcused4,tardy4,total_debauchery
id,,,,,,,,,,,,,,,,,,,,
300053,10,16,Hartford High School/HACTC,F,N,1,NaN,22,0,0,0,0,0,0,0,1,2,2,0,2
300339,12,18,Hartford High School/HACTC,F,N,0,NaN,4,2,4,13,9,6,27,15,5,36,15,7,41
300340,11,17,Hartford High School/HACTC,M,N,0,NaN,1,0,0,5,1,1,3,0,5,24,0,1,1
300344,9,15,Hartford High School/HACTC,M,N,0,NaN,0,0,0,15,0,0,0,1,0,3,0,0,1
300345,8,15,Hartford Memorial Middle School,M,N,0,504,0,0,0,3,0,1,4,0,1,5,0,3,0
300628,11,17,Hartford High School/HACTC,F,N,0,NaN,2,1,1,0,0,3,6,0,5,2,4,11,5
300630,9,15,Hartford High School/HACTC,M,N,0,504,1,0,1,0,0,0,0,1,0,2,1,2,2
300631,8,14,Hartford Memorial Middle School,F,N,0,NaN,0,0,1,1,0,0,2,1,0,0,2,0,3
300908,11,18,Hartford High School/HACTC,F,N,0,NaN,1,0,0,4,0,1,3,0,3,0,9,6,9
300909,9,17,Hartford High School/HACTC,M,N,0,IEP,27,0,1,16,0,0,5,0,0,15,0,0,0
300911,8,14,Hartford Memorial Middle School,F,N,0,504,3,0,1,0,0,0,7,0,0,9,0,0,0
301188,11,17,Hartford High School/HACTC,M,N,0,504,0,0,1,15,0,1,5,1,0,6,0,2,1
301191,8,14,Hartford Memorial Middle School,F,N,0,NaN,0,0,0,1,0,3,7,0,0,0,0,3,0
301466,11,17,Hartford High School/HACTC,F,N,0,NaN,5,0,0,7,0,2,15,1,0,5,0,1,1
301467,10,16,Hartford High School/HACTC,F,N,1,NaN,37,0,4,15,1,4,81,4,6,62,6,8,11
301743,12,19,Hartford High School/HACTC,M,N,0,NaN,6,1,1,10,1,2,9,0,3,27,5,4,7
301745,10,16,Hartford High School/HACTC,M,N,0,504,2,0,2,8,0,1,26,0,1,5,0,0,0
301747,8,14,Hartford Memorial Middle School,F,N,0,NaN,0,0,0,1,0,0,0,0,0,0,0,0,0
302027,12,19,Hartford High School/HACTC,M,N,0,NaN,9,0,2,5,0,2,12,1,2,5,0,2,1
302028,11,17,Hartford High School/HACTC,M,N,1,NaN,6,0,1,0,0,1,4,0,0,0,0,0,0
302032,9,15,Hartford High School/HACTC,F,N,0,NaN,1,0,2,1,0,0,0,1,2,0,1,0,2
302033,7,14,Hartford Memorial Middle School,M,N,0,NaN,0,0,0,0,0,0,0,1,0,0,1,1,2
302316,8,15,Hartford Memorial Middle School,F,N,1,504,1,1,0,7,0,4,0,0,2,0,0,3,1
302317,8,15,Hartford Memorial Middle School,M,N,0,NaN,0,0,0,0,0,0,0,0,2,0,0,1,0
302596,11,18,Hartford High School/HACTC,F,N,0,504,6,1,7,10,10,11,12,14,9,2,8,9,33
302600,9,15,Hartford High School/HACTC,F,N,0,NaN,0,0,0,0,0,0,0,1,0,0,0,0,1
302601,8,15,Hartford Memorial Middle School,M,N,0,NaN,0,0,0,0,0,0,2,0,2,1,0,1,0
302875,11,18,Hartford High School/HACTC,M,N,0,NaN,2,0,0,18,0,4,4,4,12,1,19,13,23
302876,11,17,Hartford High School/HACTC,F,N,0,NaN,11,0,2,20,0,2,2,0,0,13,0,2,0
302877,10,17,Hartford High School/HACTC,F,N,0,NaN,6,0,1,0,0,0,10,0,0,4,4,1,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2699976575,3,9,Ottauquechee School,F,N,0,NaN,1,0,0,0,0,0,1,0,0,0,0,0,0
2699976576,K,6,Ottauquechee School,M,N,0,NaN,0,0,0,1,0,0,5,0,1,0,0,0,0
2699976560,1,7,Ottauquechee School,M,N,1,IEP,0,0,0,4,0,1,6,0,2,0,0,0,0
2699976551,4,11,White River School,F,N,1,NaN,0,0,0,0,0,0,0,0,1,0,0,0,0
2699976552,3,9,White River School,M,N,1,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0
2699976553,K,6,White River School,M,N,1,IEP,0,0,0,1,0,0,1,0,0,0,0,0,0
2699976546,PA,5,White River School,M,N,0,IEP,0,0,0,7,0,2,7,2,1,0,0,0,2
2699976536,3,9,Ottauquechee School,M,N,1,NaN,0,0,0,1,0,0,4,0,1,0,0,0,0
2699976518,1,7,Dothan Brook School,M,N,0,NaN,0,0,0,1,0,1,3,0,0,0,0,0,0
2699976494,11,18,Hartford High School/HACTC,M,N,0,NaN,0,0,0,0,0,0,13,0,2,25,2,0,2
2699991245,11,17,Hartford High School/HACTC,M,N,1,NaN,0,0,0,0,0,0,36,26,7,44,24,21,50
2699976470,10,17,Hartford High School/HACTC,M,N,0,NaN,0,0,0,0,0,0,5,6,10,15,4,6,10
2699976450,7,12,Hartford Memorial Middle School,M,N,1,NaN,0,0,0,0,0,0,0,0,6,2,0,0,0
2699976444,2,8,White River School,M,N,1,NaN,0,0,0,0,2,4,7,4,6,0,0,0,6
2699976435,9,15,Hartford High School/HACTC,M,N,1,IEP,0,0,0,0,0,0,0,0,0,2,0,0,0
2699976426,1,7,Ottauquechee School,M,N,1,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0
2699976417,1,7,Dothan Brook School,M,N,1,NaN,0,0,0,0,0,0,3,0,6,0,0,0,0
2699976418,4,10,Dothan Brook School,F,N,0,NaN,0,0,0,0,0,0,8,0,0,0,0,0,0
2699976414,1,7,White River School,F,N,1,NaN,0,0,0,0,0,0,1,6,4,0,0,0,6
2699976415,3,10,White River School,M,N,1,NaN,0,0,0,0,0,0,5,6,4,0,0,0,6
2699976416,5,12,White River School,F,N,1,NaN,0,0,0,0,0,0,3,6,2,0,0,0,6
2699976403,5,11,Dothan Brook School,F,N,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0
2699976404,2,9,Dothan Brook School,M,N,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0
2699976371,5,11,White River School,M,N,0,IEP,0,0,0,0,0,0,0,0,0,0,0,0,0
2699976373,1,7,White River School,F,N,0,NaN,0,0,0,0,0,0,4,0,0,0,0,0,0
2699976349,8,14,Hartford Memorial Middle School,M,N,1,NaN,0,0,0,0,0,0,0,0,0,3,1,0,1
2699976316,9,16,Hartford High School/HACTC,M,Y,1,NaN,0,0,0,0,0,0,0,0,0,10,10,15,10
2699976316,4,10,White River School,M,N,1,IEP,0,0,0,0,0,0,2,0,0,0,0,0,0
2699976273,7,13,Hartford Memorial Middle School,M,N,0,NaN,0,0,0,0,0,0,0,0,0,0,0,1,0
2699976182,AW,32,Hartford High School/HACTC,F,N,0,NaN,0,0,0,0,0,0,0,0,0,16,0,0,0

In [7]:
df_adv = y1_data.drop(y1_data[(y1_data.disadvantaged == 1)].index)
df_disadv = y1_data.drop(y1_data[(y1_data.disadvantaged == 0)].index)

In [8]:
df_disadv

,grade,age,school,sex,homeless,disadvantaged,specialneeds,excused1,unexcused1,tardy1,excused2,unexcused2,tardy2,excused3,unexcused3,tardy3,excused4,unexcused4,tardy4,total_debauchery
id,,,,,,,,,,,,,,,,,,,,
300053,10,16,Hartford High School/HACTC,F,N,1,NaN,22,0,0,0,0,0,0,0,1,2,2,0,2
301467,10,16,Hartford High School/HACTC,F,N,1,NaN,37,0,4,15,1,4,81,4,6,62,6,8,11
302028,11,17,Hartford High School/HACTC,M,N,1,NaN,6,0,1,0,0,1,4,0,0,0,0,0,0
302316,8,15,Hartford Memorial Middle School,F,N,1,504,1,1,0,7,0,4,0,0,2,0,0,3,1
303158,9,15,Hartford High School/HACTC,M,N,1,IEP,1,4,5,0,2,3,1,14,4,2,24,11,44
303725,10,16,Hartford High School/HACTC,M,N,1,IEP,4,0,2,16,6,3,5,11,2,6,7,1,24
304003,10,16,Hartford High School/HACTC,M,N,1,IEP,3,0,0,15,1,0,10,0,0,10,0,1,1
304280,12,19,Hartford High School/HACTC,M,N,1,IEP,16,2,4,17,3,3,26,5,5,8,4,1,14
304559,12,18,Hartford High School/HACTC,M,N,1,IEP,25,0,0,2,3,0,10,0,0,11,4,2,7
304840,10,17,Hartford High School/HACTC,M,N,1,504,6,0,2,22,1,3,11,0,2,19,4,2,5
305686,11,17,Hartford High School/HACTC,M,N,1,NaN,5,1,1,15,0,1,12,0,2,9,3,6,4
306248,11,17,Hartford High School/HACTC,M,N,1,NaN,0,1,0,0,0,0,0,0,0,0,0,0,1
306813,10,16,Hartford High School/HACTC,M,N,1,504,20,0,8,12,1,1,22,2,5,29,2,5,5
306815,8,14,Hartford Memorial Middle School,M,N,1,NaN,0,0,0,2,0,1,0,0,0,4,0,0,0
307091,10,16,Hartford High School/HACTC,M,N,1,IEP,0,0,4,4,0,5,5,2,8,2,1,5,3
307371,12,18,Hartford High School/HACTC,M,N,1,504,10,4,5,9,4,9,10,6,7,15,15,11,29
307653,10,16,Hartford High School/HACTC,M,N,1,NaN,5,0,7,7,1,13,9,1,18,38,6,10,8
307931,10,16,Hartford High School/HACTC,M,N,1,IEP,15,1,1,15,1,1,21,3,0,1,0,0,5
308489,12,18,Hartford High School/HACTC,M,N,1,IEP,20,13,2,10,10,5,16,4,4,10,31,2,58
308774,10,17,Hartford High School/HACTC,F,Y,1,NaN,21,0,1,23,1,1,31,8,10,17,14,18,23
309336,9,15,Hartford High School/HACTC,M,N,1,NaN,9,0,1,3,1,4,7,0,1,0,0,3,1
310181,12,18,Hartford High School/HACTC,F,N,1,504,27,34,27,28,58,15,0,0,0,0,0,0,92
310464,9,15,Hartford High School/HACTC,M,N,1,NaN,0,0,0,0,0,0,7,2,0,0,0,3,2
311019,11,18,Hartford High School/HACTC,M,N,1,IEP,26,36,28,47,54,29,25,67,28,23,50,27,207
311023,8,14,Hartford Memorial Middle School,M,N,1,NaN,0,0,0,4,0,1,1,0,0,2,0,0,0
312156,11,17,Hartford High School/HACTC,M,N,1,NaN,6,2,1,7,1,4,8,12,5,9,17,8,32
312160,9,15,Hartford High School/HACTC,M,N,1,NaN,15,8,9,14,12,25,18,38,35,5,29,43,87
312439,10,16,Hartford High School/HACTC,M,N,1,504,30,2,1,66,6,5,78,26,9,61,69,26,103
312724,9,15,Hartford High School/HACTC,F,N,1,NaN,15,0,0,22,0,0,9,0,0,8,1,4,1
312725,8,14,Hartford Memorial Middle School,M,N,1,IEP,19,2,1,0,0,0,1,2,1,0,1,2,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2699992389,4,11,White River School,M,N,1,IEP,0,0,6,0,1,1,0,2,0,0,0,0,3
2699976739,3,8,Ottauquechee School,F,N,1,NaN,1,0,3,2,0,3,3,0,1,0,0,0,0
2699976740,8,13,Hartford Memorial Middle School,F,N,1,NaN,0,0,8,0,1,4,2,0,2,1,2,3,3
2699982923,PA,4,White River School,M,N,1,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0
2699976650,1,7,Ottauquechee School,F,N,1,NaN,0,0,0,2,0,0,1,0,0,0,0,0,0
2699976633,K,6,Dothan Brook School,F,N,1,NaN,8,0,3,5,2,12,4,0,3,0,0,0,2
2699976620,5,11,White River School,F,N,1,NaN,1,7,0,0,0,0,1,0,1,0,0,0,7
2699976607,1,7,Dothan Brook School,M,N,1,NaN,0,0,16,1,0,7,0,3,14,0,0,0,3
2699976598,9,15,Hartford High School/HACTC,F,Y,1,IEP,2,0,0,12,0,0,27,2,3,111,6,2,8
2699976587,2,8,White River School,M,N,1,NaN,1,0,0,1,4,2,0,0,2,0,0,0,4
2699976587,4,11,White River School,M,N,1,IEP,1,0,1,7,4,1,2,0,1,0,0,0,4
2699976588,6,13,Hartford Memorial Middle School,M,N,1,NaN,2,0,0,5,1,2,6,0,0,2,0,3,1
2699976578,PP,4,White River School,M,N,1,IEP,0,0,0,2,0,1,6,2,2,0,0,0,2
2699976560,1,7,Ottauquechee School,M,N,1,IEP,0,0,0,4,0,1,6,0,2,0,0,0,0
2699976551,4,11,White River School,F,N,1,NaN,0,0,0,0,0,0,0,0,1,0,0,0,0
2699976552,3,9,White River School,M,N,1,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0
2699976553,K,6,White River School,M,N,1,IEP,0,0,0,1,0,0,1,0,0,0,0,0,0
2699976536,3,9,Ottauquechee School,M,N,1,NaN,0,0,0,1,0,0,4,0,1,0,0,0,0
2699991245,11,17,Hartford High School/HACTC,M,N,1,NaN,0,0,0,0,0,0,36,26,7,44,24,21,50
2699976450,7,12,Hartford Memorial Middle School,M,N,1,NaN,0,0,0,0,0,0,0,0,6,2,0,0,0
2699976444,2,8,White River School,M,N,1,NaN,0,0,0,0,2,4,7,4,6,0,0,0,6
2699976435,9,15,Hartford High School/HACTC,M,N,1,IEP,0,0,0,0,0,0,0,0,0,2,0,0,0
2699976426,1,7,Ottauquechee School,M,N,1,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0
2699976417,1,7,Dothan Brook School,M,N,1,NaN,0,0,0,0,0,0,3,0,6,0,0,0,0
2699976414,1,7,White River School,F,N,1,NaN,0,0,0,0,0,0,1,6,4,0,0,0,6
2699976415,3,10,White River School,M,N,1,NaN,0,0,0,0,0,0,5,6,4,0,0,0,6
2699976416,5,12,White River School,F,N,1,NaN,0,0,0,0,0,0,3,6,2,0,0,0,6
2699976349,8,14,Hartford Memorial Middle School,M,N,1,NaN,0,0,0,0,0,0,0,0,0,3,1,0,1
2699976316,9,16,Hartford High School/HACTC,M,Y,1,NaN,0,0,0,0,0,0,0,0,0,10,10,15,10
2699976316,4,10,White River School,M,N,1,IEP,0,0,0,0,0,0,2,0,0,0,0,0,0

In [9]:
variables = ['age', 'excused1', 'unexcused1']

# Calculate correlations
corr1 = df_disadv[variables].corr()
corr2 = df_adv[variables].corr()

# Heatmap
sns.heatmap(corr1)
sns.heatmap(corr2)

In [10]:
sns.boxplot(data = y1_data, x='disadvantaged', y = 'total_debauchery', order=[0, 1])
plt.ylim(0,100)

(0, 100)

In [11]:
data = y1_data
data['disadvantaged'] = data['disadvantaged'].map({0: 'A', 1: 'D'})
data

,grade,age,school,sex,homeless,disadvantaged,specialneeds,excused1,unexcused1,tardy1,excused2,unexcused2,tardy2,excused3,unexcused3,tardy3,excused4,unexcused4,tardy4,total_debauchery
id,,,,,,,,,,,,,,,,,,,,
300053,10,16,Hartford High School/HACTC,F,N,D,NaN,22,0,0,0,0,0,0,0,1,2,2,0,2
300339,12,18,Hartford High School/HACTC,F,N,A,NaN,4,2,4,13,9,6,27,15,5,36,15,7,41
300340,11,17,Hartford High School/HACTC,M,N,A,NaN,1,0,0,5,1,1,3,0,5,24,0,1,1
300344,9,15,Hartford High School/HACTC,M,N,A,NaN,0,0,0,15,0,0,0,1,0,3,0,0,1
300345,8,15,Hartford Memorial Middle School,M,N,A,504,0,0,0,3,0,1,4,0,1,5,0,3,0
300628,11,17,Hartford High School/HACTC,F,N,A,NaN,2,1,1,0,0,3,6,0,5,2,4,11,5
300630,9,15,Hartford High School/HACTC,M,N,A,504,1,0,1,0,0,0,0,1,0,2,1,2,2
300631,8,14,Hartford Memorial Middle School,F,N,A,NaN,0,0,1,1,0,0,2,1,0,0,2,0,3
300908,11,18,Hartford High School/HACTC,F,N,A,NaN,1,0,0,4,0,1,3,0,3,0,9,6,9
300909,9,17,Hartford High School/HACTC,M,N,A,IEP,27,0,1,16,0,0,5,0,0,15,0,0,0
300911,8,14,Hartford Memorial Middle School,F,N,A,504,3,0,1,0,0,0,7,0,0,9,0,0,0
301188,11,17,Hartford High School/HACTC,M,N,A,504,0,0,1,15,0,1,5,1,0,6,0,2,1
301191,8,14,Hartford Memorial Middle School,F,N,A,NaN,0,0,0,1,0,3,7,0,0,0,0,3,0
301466,11,17,Hartford High School/HACTC,F,N,A,NaN,5,0,0,7,0,2,15,1,0,5,0,1,1
301467,10,16,Hartford High School/HACTC,F,N,D,NaN,37,0,4,15,1,4,81,4,6,62,6,8,11
301743,12,19,Hartford High School/HACTC,M,N,A,NaN,6,1,1,10,1,2,9,0,3,27,5,4,7
301745,10,16,Hartford High School/HACTC,M,N,A,504,2,0,2,8,0,1,26,0,1,5,0,0,0
301747,8,14,Hartford Memorial Middle School,F,N,A,NaN,0,0,0,1,0,0,0,0,0,0,0,0,0
302027,12,19,Hartford High School/HACTC,M,N,A,NaN,9,0,2,5,0,2,12,1,2,5,0,2,1
302028,11,17,Hartford High School/HACTC,M,N,D,NaN,6,0,1,0,0,1,4,0,0,0,0,0,0
302032,9,15,Hartford High School/HACTC,F,N,A,NaN,1,0,2,1,0,0,0,1,2,0,1,0,2
302033,7,14,Hartford Memorial Middle School,M,N,A,NaN,0,0,0,0,0,0,0,1,0,0,1,1,2
302316,8,15,Hartford Memorial Middle School,F,N,D,504,1,1,0,7,0,4,0,0,2,0,0,3,1
302317,8,15,Hartford Memorial Middle School,M,N,A,NaN,0,0,0,0,0,0,0,0,2,0,0,1,0
302596,11,18,Hartford High School/HACTC,F,N,A,504,6,1,7,10,10,11,12,14,9,2,8,9,33
302600,9,15,Hartford High School/HACTC,F,N,A,NaN,0,0,0,0,0,0,0,1,0,0,0,0,1
302601,8,15,Hartford Memorial Middle School,M,N,A,NaN,0,0,0,0,0,0,2,0,2,1,0,1,0
302875,11,18,Hartford High School/HACTC,M,N,A,NaN,2,0,0,18,0,4,4,4,12,1,19,13,23
302876,11,17,Hartford High School/HACTC,F,N,A,NaN,11,0,2,20,0,2,2,0,0,13,0,2,0
302877,10,17,Hartford High School/HACTC,F,N,A,NaN,6,0,1,0,0,0,10,0,0,4,4,1,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2699976575,3,9,Ottauquechee School,F,N,A,NaN,1,0,0,0,0,0,1,0,0,0,0,0,0
2699976576,K,6,Ottauquechee School,M,N,A,NaN,0,0,0,1,0,0,5,0,1,0,0,0,0
2699976560,1,7,Ottauquechee School,M,N,D,IEP,0,0,0,4,0,1,6,0,2,0,0,0,0
2699976551,4,11,White River School,F,N,D,NaN,0,0,0,0,0,0,0,0,1,0,0,0,0
2699976552,3,9,White River School,M,N,D,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0
2699976553,K,6,White River School,M,N,D,IEP,0,0,0,1,0,0,1,0,0,0,0,0,0
2699976546,PA,5,White River School,M,N,A,IEP,0,0,0,7,0,2,7,2,1,0,0,0,2
2699976536,3,9,Ottauquechee School,M,N,D,NaN,0,0,0,1,0,0,4,0,1,0,0,0,0
2699976518,1,7,Dothan Brook School,M,N,A,NaN,0,0,0,1,0,1,3,0,0,0,0,0,0
2699976494,11,18,Hartford High School/HACTC,M,N,A,NaN,0,0,0,0,0,0,13,0,2,25,2,0,2
2699991245,11,17,Hartford High School/HACTC,M,N,D,NaN,0,0,0,0,0,0,36,26,7,44,24,21,50
2699976470,10,17,Hartford High School/HACTC,M,N,A,NaN,0,0,0,0,0,0,5,6,10,15,4,6,10
2699976450,7,12,Hartford Memorial Middle School,M,N,D,NaN,0,0,0,0,0,0,0,0,6,2,0,0,0
2699976444,2,8,White River School,M,N,D,NaN,0,0,0,0,2,4,7,4,6,0,0,0,6
2699976435,9,15,Hartford High School/HACTC,M,N,D,IEP,0,0,0,0,0,0,0,0,0,2,0,0,0
2699976426,1,7,Ottauquechee School,M,N,D,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0
2699976417,1,7,Dothan Brook School,M,N,D,NaN,0,0,0,0,0,0,3,0,6,0,0,0,0
2699976418,4,10,Dothan Brook School,F,N,A,NaN,0,0,0,0,0,0,8,0,0,0,0,0,0
2699976414,1,7,White River School,F,N,D,NaN,0,0,0,0,0,0,1,6,4,0,0,0,6
2699976415,3,10,White River School,M,N,D,NaN,0,0,0,0,0,0,5,6,4,0,0,0,6
2699976416,5,12,White River School,F,N,D,NaN,0,0,0,0,0,0,3,6,2,0,0,0,6
2699976403,5,11,Dothan Brook School,F,N,A,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0
2699976404,2,9,Dothan Brook School,M,N,A,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0
2699976371,5,11,White River School,M,N,A,IEP,0,0,0,0,0,0,0,0,0,0,0,0,0
2699976373,1,7,White River School,F,N,A,NaN,0,0,0,0,0,0,4,0,0,0,0,0,0
2699976349,8,14,Hartford Memorial Middle School,M,N,D,NaN,0,0,0,0,0,0,0,0,0,3,1,0,1
2699976316,9,16,Hartford High School/HACTC,M,Y,D,NaN,0,0,0,0,0,0,0,0,0,10,10,15,10
2699976316,4,10,White River School,M,N,D,IEP,0,0,0,0,0,0,2,0,0,0,0,0,0
2699976273,7,13,Hartford Memorial Middle School,M,N,A,NaN,0,0,0,0,0,0,0,0,0,0,0,1,0
2699976182,AW,32,Hartford High School/HACTC,F,N,A,NaN,0,0,0,0,0,0,0,0,0,16,0,0,0

In [12]:
sns.distplot(df_adv['total_debauchery'], bins = 20)
sns.distplot(df_disadv['total_debauchery'], bins = 20)
plt.xlim(0,100)

(0, 100)

In [13]:
for d in ['A', 'D']:
    sns.distplot(data[data.disadvantaged == d]['total_debauchery'], bins = 20, label = d)
sns.plt.legend()
sns.plt.show()

In [14]:
sns.set_palette('muted')
sns.set_style('ticks')
plt.xlim(0,100)

(0, 100)